# Generated by Django 3.0.8 on 2020-07-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponse',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
